chore: various repo chores
sapphire-project/pieces pull request #2
Opened 2020-08-29 17:36 UTC by Favna

2020-08-29 17:41 UTC, Favna commented
@all-contributors add favna for code and infra

2020-08-29 17:49 UTC, vladfrangu requested changes

2020-08-29 17:49 UTC, vladfrangu commented on package.json
> +		"yarn",
What

2020-08-29 17:49 UTC, vladfrangu commented on package.json
> +		"format": "prettier --write src/**/*.ts",
This should use eslint, not prettier directly. Check how I did it https://github.com/discordjs/discord-api-types/blob/main/package.json#L60

Because this writes, and by using eslint we also can ignore any "invalid syntax according to prettier although very valid syntax otherwise"

2020-08-29 18:23 UTC, Favna commented on package.json
> +		"format": "prettier --write src/**/*.ts",
This is how all repos are set up right now. Format is also only ever ran manually. Developers are free to just run lint. 

I mean I'm all for nuking format, but then the discussion becomes should format:check also be removed at with that the CI job? And is it really worth making the change to all repos?

2020-08-29 18:24 UTC, Favna commented on package.json
> +		"yarn",
Keywords are indexing for NPM. Gotta farm that bit of SEO.

Also, this is present in all repos. It follows sapphire-template.

2020-08-29 18:29 UTC, vladfrangu commented on package.json
> +		"format": "prettier --write src/**/*.ts",
I mean `format:check` is already ran by the eslint test considering we use the prettier rules... Seems awfully redundant, does it not?

2020-08-31 23:44 UTC, Favna commented on package.json
> +		"format": "prettier --write src/**/*.ts",
done

2020-09-01 03:50 UTC, vladfrangu approved these changes

2020-09-01 07:17 UTC, kyranet approved these changes

2020-09-01 09:22 UTC, merged

2020-09-01 09:23 UTC, Favna commented
@all-contributors add favna for code and infra