feat: pieces v2!
sapphire-project/pieces pull request #29
Opened 2020-12-21 19:49 UTC by kyranet

2020-12-21 20:14 UTC, vladfrangu requested changes

2020-12-21 20:14 UTC, vladfrangu commented on src/lib/strategies/LoaderStrategy.ts
> +		return import(path);
Why not do the timestamp thing too, so we don't need a custom loader to reload pieces 👀

2020-12-21 22:18 UTC, vladfrangu approved these changes

2020-12-21 22:46 UTC, cfanoulis reviewed
minor nits

2020-12-21 22:46 UTC, cfanoulis commented on src/lib/Store.ts
> +	 * import { Store } from '(at)sapphire/pieces';
```suggestion
	 * import { Store } from '@sapphire/pieces';
```

2020-12-21 22:46 UTC, cfanoulis commented on src/lib/Store.ts
> +	 * declare module '(at)sapphire/pieces' {
```suggestion
	 * declare module '@sapphire/pieces' {
```
whats up with not using @ now

2020-12-21 22:46 UTC, cfanoulis commented on src/lib/strategies/LoaderStrategy.ts
> + * An abstracted loader interface.
Comment ≠ actual code

2020-12-21 22:48 UTC, kyranet commented on src/lib/Store.ts
> +	 * import { Store } from '(at)sapphire/pieces';
That breaks VSCode's IntelliSense.

2020-12-21 22:50 UTC, cfanoulis commented on src/lib/Store.ts
> +	 * import { Store } from '(at)sapphire/pieces';
has anyone submitted a bug report lol

anyways /resolved (cant resolve on mobile)

2020-12-21 22:50 UTC, cfanoulis commented on src/lib/Store.ts
> +	 * declare module '(at)sapphire/pieces' {
/resolved see previous comment

2020-12-21 22:55 UTC, cfanoulis approved these changes

2020-12-22 00:17 UTC, Favna approved these changes

2020-12-22 00:17 UTC, merged