feat(store): add trace logging
sapphire-project/pieces pull request #45
Opened 2021-01-05 09:45 UTC by kyranet

2021-01-05 09:55 UTC, vladfrangu requested changes

2021-01-05 09:55 UTC, vladfrangu commented on src/lib/structures/Store.ts
> +		Store.logger?.(`[STORE => ${this.name}] [INSERT] Loaded new piece '${piece.name}'.`);
this fits better before the this.set

2021-01-05 09:58 UTC, kyranet commented on src/lib/structures/Store.ts
> +		Store.logger?.(`[STORE => ${this.name}] [INSERT] Loaded new piece '${piece.name}'.`);
Loading and inserting are two different things, fixed with 57cdb64.

2021-01-05 10:00 UTC, vladfrangu approved these changes

2021-01-07 09:49 UTC, Favna approved these changes

2021-01-07 09:49 UTC, merged