docs(readme): improve readme
sapphire-project/pieces pull request #7
Opened 2020-09-05 21:04 UTC by Favna

2020-09-05 22:22 UTC, Rexogamer requested changes

2020-09-05 22:22 UTC, Rexogamer commented on README.md
> +[sapphire framework]: https://github.com/sapphire-project/framework
Capitalise it
```suggestion
[Sapphire Framework]: https://github.com/sapphire-project/framework
```

2020-09-05 22:22 UTC, Rexogamer commented on README.md
> +Sapphire's piece loader</h4>
```suggestion
Sapphire's piece loader.</h4>
```
also where's the other h4 tag

2020-09-05 22:22 UTC, Rexogamer commented on README.md
> +Pieces make up the core of the [Sapphire Framework][]. In the design of [Sapphire Framework][] every command, event, precondition and others in the root "pieces". They are pieces of your code, that m
If you're trying to suggest commands and such are pieces...
```suggestion
Pieces make up the core of the [Sapphire Framework][]. In the design of [Sapphire Framework][] your commands, events, preconditions and more are "pieces". They are pieces of your code, that make up the whole.
```

2020-09-05 22:56 UTC, Favna commented on README.md
> +[sapphire framework]: https://github.com/sapphire-project/framework
Prettier is going to lowercase it again

2020-09-05 23:09 UTC, Rexogamer commented on README.md
> +[sapphire framework]: https://github.com/sapphire-project/framework
Curse prettier

2020-09-06 06:10 UTC, kyranet approved these changes

2020-09-06 06:11 UTC, kyranet requested changes

2020-09-06 06:11 UTC, kyranet commented on README.md
> +Sapphire Project is and always will be open source, even if we don't get donations. That being said, we know there are amazing people who may still want to donate just to show their appreciation. Tha
```suggestion
Sapphire Project is and always will be open source, even if we don't get donations. That being said, we know there are amazing people who may still want to donate just to show their appreciation. Thank you very much in advance!
```

2020-09-06 16:02 UTC, kyranet approved these changes

2020-09-06 16:02 UTC, Rexogamer approved these changes

2020-09-06 16:12 UTC, merged